terminal:
  # This can be any image that has the necessary runtime environment for your project.
  image: pandagix/alpine-pandagix-docker:279889
  #before_script:
  #  - apt-get update
  #script: sleep 60
  #variables:
  #  RAILS_ENV: "test"
  #  NODE_ENV: "test"
    
